# Generated by Django 6.0 on 2025-12-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=15)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=35)),
                ('pais', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('autos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFinal.autos')),
                ('sucursales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFinal.sucursales')),
            ],
        ),
    ]
