# Generated by Django 6.0 on 2025-12-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0002_autos_sucursales_ventas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
