# Generated by Django 6.0 on 2025-12-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0003_delete_curso_delete_entregable_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos/'),
        ),
    ]
